server:
 port: 9192

spring:
 datasource:
   username: root
   password: P@sswordroot123
   url: jdbc:mysql://localhost:3306/hotel_db
   driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
   show-sql: true
   hibernate:
     ddl-auto: update
     format_sql: true
 servlet:
   multipart:
    max-file-size: 2MB
    max-request-size: 2MB
   

   security:
     jwt:
       secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
       expire-length: 3600000


















